Algoritmo "cubo"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Eliane Ribeiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/01/2019
Var
// Seção de Declarações das variáveis 
valor, cubo : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um número: ")
leia(valor)

cubo<-valor*valor*valor

escreva("O cubo do número é: ", cubo)

Fimalgoritmo