Algoritmo "semnome"
// Disciplina  :  [Lógica de Programação] 
// Professor   : Eliane Ribeiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/01/2019
Var
// Seção de Declarações das variáveis 
num : inteiro
opcao : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número de 1 a 5")
leia(num)

escolha opcao
caso num = 1
escreva("Número 1")
fimescolha

Fimalgoritmo