Algoritmo "semnome"
// Disciplina  :  [Lógica de Programação] 
// Professor   : Eliane Ribeiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/01/2019
Var
// Seção de Declarações das variáveis 
x:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   enquanto x <10 faca
   escreval(x)
   x<-x+1
   fimenquanto
   fimalgoritmo

Fimalgoritmo