Algoritmo "semnome"
// Disciplina  :  [Lógica de Programação] 
// Professor   : Eliane Ribeiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/01/2019
Var
// Seção de Declarações das variáveis 
n1, n2, media : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Informe um valor")
leia(n1)

escreval("Informe outro valor")
leia(n2)

media<- (n1+n2)/2

escreval(media)

Fimalgoritmo